---
- name: Create aliases
  brocade_zoning_alias:
    credential:
      fos_ip_addr: 172.21.0.21
      fos_user_name: admin
      fos_password: abc123!!
      https: False
    vfid: -1
    aliases:
      - name: Host1
        members:
          - aa:11:11:11:11:11:11:11
          - aa:22:22:22:22:22:22:22
      - name: Target2
        members:
          - aa:44:44:44:44:44:44:44