---
- name: Create volume group
  ibm_svc_manage_volumegroup:
    clustername: "{{ clustername }}"
    domain: "{{ domain }}"
    token: "{{ auth.token }}"
    name: "{{ host.name }}"
    state: present

- name: Add volume to volume group
  ibm_svc_manage_volume:
    clustername: "{{ clustername }}"
    domain: "{{ domain }}"
    token: "{{ auth.token }}"
    name: "{{ host.vdisk_name }}"
    volumegroup: "{{ host.name }}"
    state: present
