---
- name: Add volume to volume group
  hosts: localhost
  tasks:
    - name: Add volume to volume group
      ibm.storage_virtualize.ibm_svc_manage_volume:
        clustername: fs5200
        domain: esilabs.com
        username: rkoetter
        password: ESI@2022bpic
        name: my_volume
        volumegroup: my_volume_group
        state: "present"