---
- name: Add volume to volume group
  collections:
    - ibm.storage_virtualize
  hosts: localhost
  vars:
    clustername : fs5200
    domain : esilabs.com
    username : rkoetter
    password : ESI@2022bpic
  tasks:
    - name: Obtain an authentication token
      register: result
      ibm_svc_auth:
        clustername: "{{clustername}}"
        domain: "{{domain}}"
        username: "{{username}}"
        password: "{{password}}"
    
    - name: Get volume information
      register: volume_list
      ibm_svc_info:
        gather_subset: vol
    
    - name: Print
      debug:
        msg: "{{ volume_list }}"
      
    - name: Add volume to volume group
      ibm_svc_manage_volume:
        clustername: "{{ clustername }}"
        domain: "{{ domain }}"
        token: "{{ result.token }}"
        name: my_volume
        volumegroup: my_volume_group
        state: "present"