---
- name: Using the IBM Storage Virtualize collection
  hosts: localhost
  tasks:
    - name: Gather info from storage
      ibm.storage_virtualize.ibm_svc_info:
        clustername: fs5200
        domain:
        username: rkoetter
        password: ESI@2022bpic
        log_path: ../logs/fs5200.log
        gather_subset: all