---
- name: Add volume to volume group
  collections:
    - ibm.storage_virtualize
  hosts: localhost
  gather_facts: no
  vars:
    clustername : fs5200
    domain : esilabs.com
    username : rkoetter
    password : ESI@2022bpic
  tasks:
    - name: Obtain an authentication token
      register: result
      ibm_svc_auth:
        clustername: "{{clustername}}"
        domain: "{{domain}}"
        username: "{{username}}"
        password: "{{password}}"
    
    - name: Get volume information
      register: volume_list
      ibm_svc_info:
        clustername: "{{ clustername }}"
        domain: "{{ domain }}"
        token: "{{ result.token }}"
        gather_subset: vol

    - name: Get host information
      register: hostmap_list
      ibm_svc_info:
        clustername: "{{ clustername }}"
        domain: "{{ domain }}"
        token: "{{ result.token }}"
        gather_subset: hostvdiskmap
    
    - name: Loop through each host map
      ibm_svc_manage_volume:
        clustername: "{{ clustername }}"
        domain: "{{ domain }}"
        token: "{{ result.token }}"
        name: "{{ item.vdisk_name }}"
        volumegroup: "{{ item.name }}"
      debug:
        msg: "Host: {{ item.name }} Volume: {{ item.vdisk_name }}"
      loop:
        "{{ hostmap_list.HostVdiskMap }}"

        # - name: Check if the volume is in a volume group
        #   ibm.storage_virtualize.svc_info_volume_group:
        #     array_hostname: "{{ ansible_host }}"
        #     name: "{{ volume.name }}"
        #   register: volume_group_info
        #   ignore_errors: yes

        # - name: Create volume group if not exists
        #   when: volume_group_info.volume_group is not defined
        #   ibm.storage_virtualize.svc_manage_volume_group:
        #     array_hostname: "{{ ansible_host }}"
        #     name: "{{ volume.mapping_to_host }}"
        #     state: present

        # - name: Add volume to volume group
        #   when: volume_group_info.volume_group is not defined
        #   ibm.storage_virtualize.svc_manage_volume_group:
        #     array_hostname: "{{ ansible_host }}"
        #     name: "{{ volume.mapping_to_host }}"
        #     volume: "{{ volume.name }}"
        #     state: present
      
    # - name: Add volume to volume group
    #   ibm_svc_manage_volume:
    #     clustername: "{{ clustername }}"
    #     domain: "{{ domain }}"
    #     token: "{{ result.token }}"
    #     name: my_volume
    #     volumegroup: my_volume_group
    #     state: "present"