---
- name: Add volume to volume group
  collections:
    - ibm.storage_virtualize
  hosts: localhost
  gather_facts: no
  vars:
    clustername: fs5200
    domain: esilabs.com
    username: rkoetter
    password: ESI@2022bpic
  tasks:
    - name: Obtain an authentication token
      register: auth
      ibm_svc_auth:
        clustername: "{{ clustername }}"
        domain: "{{ domain }}"
        username: "{{ username }}"
        password: "{{ password }}"

    - name: Get volume information
      register: volume_list
      ibm_svc_info:
        clustername: "{{ clustername }}"
        domain: "{{ domain }}"
        token: "{{ auth.token }}"
        gather_subset: vol

    - name: Get host information
      register: hostmap_list
      ibm_svc_info:
        clustername: "{{ clustername }}"
        domain: "{{ domain }}"
        token: "{{ auth.token }}"
        gather_subset: hostvdiskmap

    - name: Loop through each host map and add to volume group
      include_tasks: fs_create_add_vols_volgrp.yml
      loop: "{{ hostmap_list.HostVdiskMap }}"
      loop_control:
        loop_var: host