---
- name: Add volume to volume group
  hosts: localhost
  tasks:
    - name: Add volume to group
      ibm.storage_virtualize.ibm_sv_manage_storage_partition:
        clustername: fs5200
        domain: 
        username: rkoetter
        password: ESI@2022bpic
        vol_name: my_volume
        vol_group_name: my_volume_group
        state: present