---
- name: Installing and running Apache
  hosts: localhost

  tasks:
          - name: Install Apache
            dnf:
                    name: httpd
                    state: present

          - name: start httpd
            service:
                    name: httpd
                    state: started
