---
- name: Test IBM Storage Virtualize Volume Creation
  hosts: localhost
  collections:
    ibm.storage_virtualize
  gather_facts: no
  vars:
    - clustername: fs9200-cluster1.esilabs.com
    - username: rkoetter
    - password: ESI@2022bpic
    - pool: Pool0
    - volname: Ansible_Test_vol_3
    - hostname: Ansible_Test_host_1
    - fcwwpn_list: 100000109B570216:1000001AA0570266
  connection: local
  tasks:
    - name: Fetch authorization token
      register: auth
      ibm_svc_auth:
        clustername: "{{clustername}}"
        username: "{{username}}"
        password: "{{password}}"
    - name: create volume
      ibm_svc_manage_volume:
        clustername: "{{clustername}}"
        token: "{{auth.token}}"
        pool: "{{pool}}"
        name: "{{volname}}"
        size: 10
        unit: "gb"
        state: present
    - name: Define a new FC host
      ibm.storage_virtualize.ibm_svc_host:
        clustername: "{{clustername}}"
        token: "{{auth.token}}"
        # log_path: /tmp/playbook.debug
        name: "{{hostname}}"
        state: present
        fcwwpn: "{{fcwwpn_list}}"
        iogrp: 0:1:2:3
        protocol: scsi
        type: generic
        # site: site-name
    - name: Map a volume to a host
      ibm.storage_virtualize.ibm_svc_vol_map:
        clustername: "{{clustername}}"
        token: "{{auth.token}}"
        # log_path: /tmp/playbook.debug
        volname: "{{volname}}"
        host: "{{hostname}}"
        scsi: 1
        state: present
